name: search_instrutores
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_riverpod: ^3.0.0
  flutter_slidable: ^4.0.0
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  http: ^1.3.0
  mask_text_input_formatter: ^2.9.0
  path: ^1.9.1
  path_provider: ^2.1.5
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.4+4
  window_manager: ^0.5.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  fl_chart: ^1.1.1
  dio: ^5.9.0
  open_filex: ^4.7.0
  tutorial_coach_mark: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/credenciais-google.json
    - assets/iconBusca.png

flutter_launcher_icons:
  macos:
    generate: true
    image_path: "assets/iconBusca.png"
  windows:
    generate: true
    image_path: "assets/iconBusca.png"
  image_path: "assets/iconBusca.png"
